const SET_CARD = 'SET_CARD';
const SET_CARDS = 'SET_CARDS';
const DELETE_CARD = 'DELETE_CARD';

const SET_USER = 'SET_USER';
const SET_USER_CARDS = 'SET_USER_CARDS';
const ADD_USER_CARD = 'ADD_USER_CARD';
const DELETE_USER_CARD = 'DELETE_USER_CARD';

const REMOVE_LIKE = 'REMOVE_LIKE';
const ADD_LIKE = 'ADD_LIKE';

const SHOW_PLACE_POPUP = 'SHOW_PLACE_POPUP';
const SHOW_EDIT_POPUP = 'SHOW_EDIT_POPUP';

export {
  SET_CARD,
  SET_CARDS,
  DELETE_CARD,
  SET_USER,
  SET_USER_CARDS,
  ADD_USER_CARD,
  DELETE_USER_CARD,
  REMOVE_LIKE,
  ADD_LIKE,
  SHOW_PLACE_POPUP,
  SHOW_EDIT_POPUP,
};
