const SET_CARD = 'SET_CARD';
const SET_CARDS = 'SET_CARDS';
const DELETE_CARD = 'DELETE_CARD';
const SET_USER = 'SET_USER';
const SET_USER_CARDS = 'SET_USER_CARDS';
const ADD_USER_CARD = 'ADD_USER_CARD';
export {
  SET_CARD,
  SET_CARDS,
  DELETE_CARD,
  SET_USER,
  SET_USER_CARDS,
  ADD_USER_CARD,
};
